config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    root to: "users#index"
  end

  root to: 'visitors#index'
  devise_for :users
  resources :users

  resources :clients
  resources :raids
  resources :raids_clients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_paper_trail

  has_many :raids_clients
  has_many :raids, through: :raids_clients
  has_many :criminal_histories

  validates :name, presence: true
end

app/models/criminal_history.rb
class CriminalHistory < ApplicationRecord
end

app/models/raid.rb
class Raid < ApplicationRecord
  has_paper_trail

  has_many :raids_clients
  has_many :clients, through: :raids_clients

  validates :address, :type_of_raid, :zip_code, :raided_at, presence: true

  scope :sort_by_time, -> { order(raided_at: :asc) }

  def to_s
    "#{type_of_raid} - #{zip_code}:#{raided_at}"
  end
end

app/models/raids_client.rb
class RaidsClient < ApplicationRecord
  has_paper_trail

  belongs_to :raid
  belongs_to :client
end

app/models/user.rb
class User < ApplicationRecord
  has_paper_trail

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin
    before_action :set_paper_trail_whodunnit

    def authenticate_admin
      redirect_to root_path, alert: 'Not authorized.' unless current_user.try(:admin?)
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_paper_trail_whodunnit

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/clients_controller.rb
class ClientsController < AuthenticatedController
  def index
    @clients = Client.all
  end

  def edit
    @client = Client.where(id: params[:id]).first
  end

  def new
    @client = Client.new
  end

  def show
    @client = Client.where(id: params[:id]).first
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client
    else
      render 'new'
    end
  end

  private

  def client_params
    params.require(:client).permit(
      :address,
      :contact_phone_number,
      :country_of_origin,
      :family_in_us,
      :gender,
      :name,
      :notes,
      :started_us_residence_at
    )
  end
end

app/controllers/raids_clients_controller.rb
class RaidsClientsController < AuthenticatedController
  def new
    if params['raid_id']
      @raid = Raid.where(id: params['raid_id']).first
    else
      fail "No raid provided!"
    end

    @raids_client = RaidsClient.new(raid_id: @raid.id)
  end

  def create
    @raids_client = RaidsClient.where(raids_client_params.slice(:raid_id, :client_id)).first_or_create do |rc|
      rc.notes = raids_client_params[:notes]
      rc.arrested = raids_client_params[:arrested]
    end

    if @raids_client.save
      redirect_to @raids_client.raid
    else
      render 'new'
    end
  end

  def raids_client_params
    params.require(:raids_client).permit(
      :raid_id,
      :client_id,
      :arrested,
      :notes
    )
  end
end

app/controllers/raids_controller.rb
class RaidsController < AuthenticatedController
  def index
    @raids = Raid.sort_by_time
  end

  def edit
    @raid = Raid.where(id: params[:id]).first
  end

  def new
    @raid = Raid.new
  end

  def show
    @raid = Raid.where(id: params[:id]).first
  end

  def create
    @raid = Raid.new(raid_params)

    if @raid.save
      redirect_to @raid
    else
      render 'new'
    end
  end

  private

  def raid_params
    params.require(:raid).permit(
      :address,
      :age_of_answerer,
      :how_did_ice_make_its_presence_known,
      :name_of_answerer,
      :narrative_of_door_interaction,
      :narrative_of_entrance,
      :narrative_of_interaction_inside_home,
      :raided_at,
      :type_of_raid,
      :zip_code,
      :notes
    )
  end
end

app/controllers/users_controller.rb
class UsersController < AuthenticatedController
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
  def gender_options
    [['Male', 'm'], ['Female', 'f'], ['Other', 'o']]
  end

  def country_options
    @country_options ||= ISO3166::Country.countries.sort_by(&:name).map { |c| [c.name, c.alpha2] }
  end
end

app/views/clients/_client.html.haml
%tr
  %td
    = client.name
  %td
    = client.address
  %td
    = client.gender
  %td
    = client.country_of_origin
  %td
    = client.started_us_residence_at
  %td
    = client.family_in_us
  %td
    = client.notes
  %td
    = client.contact_phone_number
  %td
    = link_to 'show', client_path(client)
  %td
    = link_to 'edit', edit_client_path(client)

app/views/clients/_clients_table.html.haml
.col-lg-12
  %table.table.table-bordered
    %thead
      %tr
        %th
          name
        %th
          address
        %th
          gender
        %th
          country of origin
        %th
          started us residence at
        %th
          family in us
        %th
          notes
        %th
          contact phone number
        %th
          show
        %th
          edit
    %tbody
      = render clients

app/views/clients/_form.html.haml
= semantic_form_for(@client, html: { class: 'form-horizontal' }) do |f|
  = f.semantic_errors(*f.object.errors.keys)

  .form-group
    = f.label :name, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :address, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.text_field :address, class: 'form-control'
  .form-group
    = f.label :gender, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.select :gender, gender_options, include_blank: true, class: 'form-control'
  .form-group
    = f.label :country_of_origin, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.select :country_of_origin, country_options, include_blank: true, class: 'form-control'
  .form-group
    = f.label :started_us_residence_at, class: 'col-sm-4 control-label'
    .col-sm-4
      = f.date_field :started_us_residence_at, class: 'form-control'
  .form-group
    = f.label :family_in_us?, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.check_box :family_in_us, class: 'form-control'
  .form-group
    = f.label :contact_phone_number, class: 'col-sm-4 control-label'
    .col-sm-4
      = f.telephone_field :contact_phone_number, class: 'form-control'
  .form-group
    = f.label :notes, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.text_area :notes, class: 'form-control'

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/clients/edit.html.haml
%h1 Edit Client

= render 'form'

app/views/clients/index.html.haml
%h2
  = link_to 'Create New Client', new_client_path

= render partial: 'clients_table', locals: { clients: @clients }

app/views/clients/new.html.haml
%h1 New Client

- if @client.errors.any?
  %h4
    = pluralize(@client.errors.count, "error")
    prohibited this article from being saved
  %ul
    - @client.errors.full_messages.each do |msg|
      %li= msg

= render 'form'

app/views/clients/show.html.haml
= render partial: 'clients_table', locals: { clients: [@client] }

%h2 Raids Involved In
= render partial: 'raids/raids_table', locals: { raids: @client.raids.sort_by_time }

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
%ul.navbar-nav
  - if user_signed_in?
    %li.nav-item.dropdown
      = link_to(current_user.email, root_path, class: 'nav-link dropdown-toggle btn btn-outline-secondary', id: 'navbarDropdownMenuLink', data: { toggle: 'dropdown' }, 'aria-haspopup': "true", 'aria-expanded': "false")
      .dropdown-menu{ 'aria-labelledby': "navbarDropdownMenuLink" }
        = link_to 'Edit account', edit_user_registration_path, class: 'dropdown-item'
        = link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'dropdown-item'
        - if current_user.admin?
          = link_to 'Admin', '/admin', class: 'dropdown-item'
          = link_to 'Users', users_path, class: 'dropdown-item'

  - else
    %li.nav-item= link_to 'Sign in', new_user_session_path, class: 'nav-link'
    %li.nav-item= link_to 'Sign up', new_user_registration_path, class: 'nav-link'

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-toggleable-md.navbar-inverse.bg-inverse
  %button.navbar-toggler.navbar-toggler-right{ type: :button, data: { toggle: 'collapse', target: '#navbarNav' }, 'aria-controls': "navbarNav", 'aria-expanded': "false", 'aria-label': "Toggle navigation" }
    %span.navbar-toggler-icon

  = link_to 'Rader', root_path, class: 'navbar-brand'
  = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
#navbarNav.collapse.navbar-collapse
  - if user_signed_in?
    %ul.navbar-nav.mr-auto
      %li.nav-item= link_to('Clients', clients_path, class: 'nav-link')
      %li.nav-item= link_to('Raids', raids_path, class: 'nav-link')

  = render 'layouts/nav_links_for_auth'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    %title= content_for?(:title) ? yield(:title) : 'Rader'
    %meta{name: 'description', content: (content_for?(:description) ? yield(:description) : 'Rader')}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    .container
      = render 'layouts/messages'
      = yield
-#  %main{role: 'main'}

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/raids/_form.html.haml
= form_for(@raid, html: { class: 'form-horizontal' }) do |f|
  .form-group
    = f.label :type_of_raid, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.select :type_of_raid, ['home', 'street', 'workplace', 'shelter'], include_blank: false, class: 'form-control'
  .form-group
    = f.label :date_and_time_of_raid, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.datetime_field :raided_at, class: 'form-control'
  .form-group
    = f.label :address, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.text_field :address, class: 'form-control'
  .form-group
    = f.label :zip_code, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.number_field :zip_code, class: 'form-control'
  .form-group
    = f.label :name_of_answerer, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.text_field :name_of_answerer, class: 'form-control'
  .form-group
    = f.label :age_of_answerer, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.number_field :age_of_answerer, in: 1..110, class: 'form-control'
  .form-group
    = f.label :how_did_ice_make_its_presence_known?, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.text_area :how_did_ice_make_its_presence_known, class: 'form-control'
  .form-group
    = f.label :narrative_of_door_interaction, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.text_area :narrative_of_door_interaction, class: 'form-control'
  .form-group
    = f.label :narrative_of_entrance, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.text_area :narrative_of_entrance, class: 'form-control'
  .form-group
    = f.label :narrative_of_interaction_inside_building, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.text_area :narrative_of_interaction_inside_home, class: 'form-control'
  .form-group
    = f.label :how_did_ice_respond_to_any_medical_issues, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.text_area :response_to_medical_issues, class: 'form-control'
  .form-group
    = f.label :how_did_ice_respond_to_any_childcare_issues, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.text_area :response_to_childcare_issues, class: 'form-control'
  .form-group
    = f.label :were_other_arrests_made_during_raid?, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.text_area :other_arrests, class: 'form-control'
  .form-group
    = f.label :asked_others_for_documents_or_fingerprints?, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.text_area :asked_others_for_documents_or_fingerprints, class: 'form-control'

  .form-group
    = f.label :notes, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.text_area :notes, class: 'form-control'

  .form-actions
    = f.button :submit

app/views/raids/_raid.html.haml
%tr
  %td
    = raid.type_of_raid
  %td
    = raid.raided_at
  %td
    = raid.zip_code
  %td
    = raid.clients.size
  %td
    = raid.raids_clients.select(&:arrested).size
  %td
    = raid.name_of_answerer
  %td
    = raid.age_of_answerer
  %td
    = raid.how_did_ice_make_its_presence_known
  %td
    = raid.narrative_of_door_interaction
  %td
    = raid.narrative_of_entrance
  %td
    = raid.narrative_of_interaction_inside_home
  %td
    = raid.response_to_medical_issues
  %td
    = raid.response_to_childcare_issues
  %th
    = raid.other_arrests
  %td
    = raid.notes
  %td
    = link_to 'show', raid_path(raid)
  %td
    = link_to 'edit', edit_raid_path(raid)

app/views/raids/_raids_table.html.haml
.col-lg-12
  %table.table.table-bordered
    %thead
      %tr
        %th
          type of raid
        %th
          raided at
        %th
          zip code
        %th
          number of clients involved
        %th
          number of arrests
        %th
          name of answerer
        %th
          age of answerer
        %th
          how did ice make its presence known
        %th
          narrative of door interaction
        %th
          narrative of entrance
        %th
          narrative of interaction inside home
        %th
          how did they respond to any medical issues
        %th
          how did they respond to any childcare issues
        %th
          were other arrests made?
        %th
          notes
        %th
          show
        %th
          edit
    %tbody
      = render raids

app/views/raids/edit.html.haml
%h1 Edit Raid

= render 'form'

app/views/raids/index.html.haml
%h2
  = link_to 'Create New Raid', new_raid_path

= render partial: 'raids_table', locals: { raids: @raids }

app/views/raids/new.html.haml
%h1 New Raid

- if @raid.errors.any?
  %h4
    = pluralize(@raid.errors.count, "error")
    prohibited this article from being saved
  %ul
    - @raid.errors.full_messages.each do |msg|
      %li= msg

= render 'form'

app/views/raids/show.html.haml
= render partial: 'raids_table', locals: { raids: [@raid] }

%h3 Clients Impacted
= render partial: 'clients/clients_table', locals: { clients: @raid.clients }

= link_to 'Add client to raid', controller: 'raids_clients', action: :new, raid_id: @raid.id

app/views/raids_clients/_form.html.haml
= form_for(@raids_client, html: { class: 'form-horizontal' }) do |f|
  .form-group
    = f.label :raid, class: 'col-sm-4 control-label'
    .col-sm-10
      = @raids_client.raid.to_s
      = f.hidden_field :raid_id, value: @raids_client.raid.id
  .form-group
    = f.label :client, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.collection_select(:client_id, Client.all, :id, :name)
  .form-group
    = f.label :arrested?, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.check_box :arrested, class: 'form-control'
  .form-group
    = f.label :notes, class: 'col-sm-4 control-label'
    .col-sm-10
      = f.text_area :notes, class: 'form-control'

  .form-actions
    = f.button :submit

app/views/raids_clients/new.html.haml
%h1 New Raid<->Client Link

= render 'form'

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>